In [11]:
import pandas as pd

from sklearn.preprocessing import (
    RobustScaler, MinMaxScaler, 
    OneHotEncoder, OrdinalEncoder, LabelEncoder
)

In [12]:
df = pd.read_csv("../Data/Cleaned_dataset.csv")
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
1,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
2,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
3,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
4,21,9900,OWN,2.0,VENTURE,A,2500,7.14,1,0.25,N,2

# One-hot encoding for Multi-Category column

In [13]:
#One-hot encoding for 
person_home_ownership_dummy = pd.get_dummies(
    df['person_home_ownership'],
    prefix='person_home_ownership',
    drop_first=True
).astype('int')

In [14]:
loan_intent_dummy = pd.get_dummies(
    df['loan_intent'],
    prefix='loan_intent',
    drop_first=True
).astype('int')

The Reason for one-hot encoding is that there is no order in the data

In [ ]:
#concating dummy column with main dataset
df = pd.concat([df, person_home_ownership_dummy, loan_intent_dummy], axis=1)
df = df.drop(['person_home_ownership', 'loan_intent'], axis=1)

,person_age,person_income,person_emp_length,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE
0,21,9600,5.0,B,1000,11.14,0,0.10,N,2,0,1,0,1,0,0,0,0
1,25,9600,1.0,C,5500,12.87,1,0.57,N,3,0,0,0,0,0,1,0,0
2,23,65500,4.0,C,35000,15.23,1,0.53,N,2,0,0,1,0,0,1,0,0
3,24,54400,8.0,C,35000,14.27,1,0.55,Y,4,0,0,1,0,0,1,0,0
4,21,9900,2.0,A,2500,7.14,1,0.25,N,2,0,1,0,0,0,0,0,1

# Ordinal encoding for "loan_grade" column

In [ ]:
grade_map = {
    'A':0,
    'B':1,
    'C':2,
    'D':3,
    'E':4,
    'F':5,
    'G':6,
}
df['loan_grade'] = df['loan_grade'].map(grade_map)

Data in order, for here I use ordinal encoding

# Label encoding for "cb_person_default_on_file" column

In [17]:
cb_map = {
    'Y':1, 'N':0
}
df['cb_person_default_on_file'] = df['cb_person_default_on_file'].map(cb_map)

In [18]:
df.head()

,person_age,person_income,person_emp_length,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE
0,21,9600,5.0,5,1000,11.14,0,0.10,0,2,0,1,0,1,0,0,0,0
1,25,9600,1.0,4,5500,12.87,1,0.57,0,3,0,0,0,0,0,1,0,0
2,23,65500,4.0,4,35000,15.23,1,0.53,0,2,0,0,1,0,0,1,0,0
3,24,54400,8.0,4,35000,14.27,1,0.55,1,4,0,0,1,0,0,1,0,0
4,21,9900,2.0,6,2500,7.14,1,0.25,0,2,0,1,0,0,0,0,0,1

All Feature Encoding done

# New Feature Extraction