In [28]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score, 
    confusion_matrix, 
    classification_report, 
    roc_auc_score,
    f1_score,
    recall_score
)

In [29]:
df = pd.read_csv("../Data/Preprocessed_data.csv")
df.head()

,Unnamed: 0,person_age,person_income,person_monthly_income,person_emp_length,emp_stability,loan_grade,loan_amnt,interest_loan_ratio,total_debt_load,...,debt_burden_index,cb_person_cred_hist_length,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE
0,0,3.091042,9.169623,6.685861,1.791759,0.215111,1,6.908755,4.722064,0.113329,...,0.113329,1.098612,0,1,0,1,0,0,0,0
1,1,3.258097,9.169623,6.685861,0.693147,0.039221,2,8.612685,6.563644,0.500775,...,0.500775,1.386294,0,0,0,0,0,1,0,0
2,2,3.178054,11.089821,8.605081,1.609438,0.157004,2,10.463132,8.581388,0.482426,...,0.482426,1.098612,0,0,1,0,0,1,0,0
3,3,3.218876,10.904138,8.419433,2.197225,0.285179,2,10.463132,8.516293,0.553885,...,0.553885,1.609438,0,0,1,0,0,1,0,0
4,4,3.091042,9.200391,6.716595,1.098612,0.095310,0,7.824446,5.190175,0.239017,...,0.239017,1.098612,0,1,0,0,0,0,0,1

In [30]:
df = df.drop(['Unnamed: 0'], axis=1)

In [31]:
df.head()

,person_age,person_income,person_monthly_income,person_emp_length,emp_stability,loan_grade,loan_amnt,interest_loan_ratio,total_debt_load,loan_int_rate,...,debt_burden_index,cb_person_cred_hist_length,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE
0,3.091042,9.169623,6.685861,1.791759,0.215111,1,6.908755,4.722064,0.113329,2.496506,...,0.113329,1.098612,0,1,0,1,0,0,0,0
1,3.258097,9.169623,6.685861,0.693147,0.039221,2,8.612685,6.563644,0.500775,2.629728,...,0.500775,1.386294,0,0,0,0,0,1,0,0
2,3.178054,11.089821,8.605081,1.609438,0.157004,2,10.463132,8.581388,0.482426,2.786861,...,0.482426,1.098612,0,0,1,0,0,1,0,0
3,3.218876,10.904138,8.419433,2.197225,0.285179,2,10.463132,8.516293,0.553885,2.725890,...,0.553885,1.609438,0,0,1,0,0,1,0,0
4,3.091042,9.200391,6.716595,1.098612,0.095310,0,7.824446,5.190175,0.239017,2.096790,...,0.239017,1.098612,0,1,0,0,0,0,0,1

In [32]:
x = df.drop(['loan_status'], axis=1)
y = df['loan_status']

In [33]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42)

In [34]:
lr = LogisticRegression()

lr_model = lr.fit(xtrain, ytrain)

In [36]:
print(f"Train Score: {lr_model.score(xtrain, ytrain)}")
print(f"Test Score: {lr_model.score(xtest, ytest)}")
lr_pred = lr_model.predict(xtest)
print(f"Accuracy: {accuracy_score(ytest, lr_pred)}")
print(f"Confussion Matrix:\n{confusion_matrix(ytest, lr_pred)}")

Train Score: 0.8536004760960128
Test Score: 0.8679784195493494
Accuracy: 0.8679784195493494
Confussion Matrix:
[[4749  204]
 [ 628  721]]

In [37]:
rf = RandomForestClassifier()

rf_model = rf.fit(xtrain, ytrain)
print(f"Train Score: {rf_model.score(xtrain, ytrain)}")
print(f"Test Score: {rf_model.score(xtest, ytest)}")
rf_pred = rf_model.predict(xtest)
print(f"Accuracy: {accuracy_score(ytest, rf_pred)}")
print(f"Confussion Matrix:\n{confusion_matrix(ytest, rf_pred)}")

Train Score: 0.9999603253322753
Test Score: 0.9343065693430657
Accuracy: 0.9343065693430657
Confussion Matrix:
[[4919   34]
 [ 380  969]]